
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CandidatosSistema.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Requisicion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Requisicion()
    {

        this.AsignacionRequisicion = new HashSet<AsignacionRequisicion>();

    }


    public int RequisicionId { get; set; }

    public string RequisicionTitulo { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}",ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> RequisicionFecha { get; set; }

    public Nullable<int> RequisicionAreaId { get; set; }

    public Nullable<int> RequisicionLocalidadId { get; set; }

    public string Delegacion_Municipio { get; set; }

    public Nullable<int> RequisicionSueldoId { get; set; }

    public string DescripcionRequisicion { get; set; }

    public Nullable<int> RequisicionEstatusId { get; set; }

    public string CometarioRequisicion { get; set; }

    public Nullable<int> CantidadRequisicion { get; set; }

    public Nullable<int> EmpresaId { get; set; }

    public Nullable<int> UsuarioRequisicionId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsignacionRequisicion> AsignacionRequisicion { get; set; }

    public virtual Empresa Empresa { get; set; }

    public virtual RequisicionArea RequisicionArea { get; set; }

    public virtual RequisicionEstatus RequisicionEstatus { get; set; }

    public virtual RequisicionLocalidad RequisicionLocalidad { get; set; }

    public virtual RequisicionSueldo RequisicionSueldo { get; set; }

    public virtual UsuarioRequisicion UsuarioRequisicion { get; set; }

}

}
