
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CandidatosSistema.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UsuarioRequisicion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UsuarioRequisicion()
    {

        this.Requisicion = new HashSet<Requisicion>();

    }


    public int UsuarioRequisicionId { get; set; }

 

    public string Usuario { get; set; }

    public string Contecraseña { get; set; }


    public string Correo { get; set; }

    public Nullable<bool> EstadoUsuario { get; set; }

    public Nullable<System.DateTime> FechaAlta { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Requisicion> Requisicion { get; set; }

}

}
